name: Publish
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    if: github.repository == 'KyanBirb/world-casting'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 21
          cache: gradle

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Execute gradle build
        run: ./gradlew build

      - name: Publish mods
        run: ./gradlew publish
        env:
          MAVEN_USER: ${{ vars.MAVEN_USER }}
          MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}